import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  main: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '6rem',
    minHeight: '100vh',
  },
  vercelLogo: {
    filter: 'invert(1)',
  },
  description: {
    display: 'inherit',
    justifyContent: 'inherit',
    alignItems: 'inherit',
    fontSize: '0.85rem',
    maxWidth: 'var(--max-width)',
    width: '100%',
    zIndex: '2',
    fontFamily: 'var(--font-mono)',
  },
  card: {
    padding: '1rem 1.2rem',
    borderRadius: 'var(--border-radius)',
    background: 'rgba(var(--card-rgb), 0)',
    border: '1px solid rgba(var(--card-border-rgb), 0)',
    transition: 'background 200ms, border 200ms',
  },
  code: {
    fontWeight: '700',
    fontFamily: 'var(--font-mono)',
  },
  hero: {
    display: 'flex',
    position: 'relative',
    placeItems: 'center',
  },
  heroContent: {
    display: 'flex',
    position: 'relative',
    zIndex: '0',
    paddingBottom: '4rem',
    flexDirection: 'column',
    gap: '2rem',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: 'auto',
    fontFamily:
      'system-ui, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    paddingTop: '48px',
  },
  logos: {
    display: 'flex',
    zIndex: '50',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(25%, auto))',
    maxWidth: '100%',
    width: 'var(--max-width)',
  },
  circles: {
    position: 'absolute',
    minWidth: '614px',
    minHeight: '614px',
    pointerEvents: 'none',
  },
  logo: {
    zIndex: '50',
    width: '120px',
    height: '120px',
  },
  logoGradientContainer: {
    display: 'flex',
    position: 'absolute',
    zIndex: '50',
    justifyContent: 'center',
    alignItems: 'center',
    width: '16rem',
    height: '16rem',
  },
  turborepoWordmarkContainer: {
    display: 'flex',
    zIndex: '50',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    flexDirection: 'column',
    gap: '1.25rem',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  turborepoWordmark: {
    width: '160px',
    fill: 'white',
  },
  button: {
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    borderStyle: 'none',
    boxSizing: 'border-box',
    color: '#000000',
    cursor: 'pointer',
    display: 'inline-block',
    fontSize: '16px',
    height: '40px',
    lineHeight: '20px',
    listStyle: 'none',
    margin: '0',
    outline: 'none',
    padding: '10px 16px',
    position: 'relative',
    textAlign: 'center',
    textDecoration: 'none',
    transition: 'color 100ms',
    verticalAlign: 'baseline',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    touchAction: 'manipulation',
  },
};
